import {StrictMode,useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ClerkProvider,SignIn,SignUp,useAuth,useClerk} from '@clerk/react';
import {Leaf,Sparkles,BookOpen,CalendarDays,Ellipsis,Users,UserRound,ArrowUpRight,Play,Pause,X,SkipBack,SkipForward,WifiOff,ChevronLeft} from 'lucide-react';
import {config} from './config';
import {makeClient,result,rpc,profileColumns,signedURL,cleanCopy,type DB,type Profile,type Practice,type Circle} from './data';
import {MemberProvider} from './context';
import {Page,Loading,ErrorBox,LinkCard,useLoad,useRoute,useAction} from './ui';
import {CheckIn,Toolkit,PracticeView,Reset,Gatherings} from './catalog';
import {Journal,WriteJournal,JournalEntry,ReflectionHistory} from './journal';
import {IntentionEditor} from './intention-editor';
import {ProfileView,Intake,Blocked,Guide} from './profile';
import {Circles,Chat,Directory,Moderation} from './circle';
import {connectAudioSession} from './audio-session';
import {CircleIcon} from './circle-icon';
import {NavigationDrawer} from './navigation-drawer';
import {followVisibleViewport} from './visible-viewport';
import './style.css';
import './native-parity.css';
function Brand(){return <img className="brand" src="/app/assets/wordmark.png" alt="Well-Vie"/>;}
function Login(){const panel=useRef<HTMLElement>(null);useEffect(()=>panel.current?followVisibleViewport(panel.current):undefined,[]);const invitation=new URLSearchParams(location.search).has('__clerk_ticket');return <main ref={panel} className="login-page"><div className="login-card"><Brand/><h1>A quiet place to return to.</h1><p className="login-intro">Well-Vie is invite only. Sign in with the email address you were invited with.</p>{invitation?<SignUp routing="hash" forceRedirectUrl="/app/" signInUrl="/app/"/>:<SignIn routing="hash" forceRedirectUrl="/app/"/>}<p className="small muted">Need a hand? <a href="mailto:mckenzie@well-vie.com">Contact Well-Vie</a></p></div></main>;}
function Connected(){const {isLoaded,isSignedIn,userId,sessionId,getToken}=useAuth();const clerk=useClerk();const token=useRef(getToken);token.current=getToken;const db=useMemo(()=>makeClient(()=>token.current()),[userId,sessionId]);const signOut=async()=>{await db.removeAllChannels();await clerk.signOut({redirectUrl:'/app/'});};if(!isLoaded)return <Loading/>;if(!isSignedIn)return <Login/>;return <MemberApp key={userId+':'+sessionId} db={db} signOut={signOut}/>;}

function MemberApp({db,signOut}:{db:DB;signOut:()=>Promise<void>}){const {route,go}=useRoute();const load=useLoad(async()=>{const member=await rpc<{id:string;isAdmin:boolean}|null>(db,'current_member_context');if(!member)return null;return result<Profile>(db.from('profiles').select(profileColumns).eq('id',member.id).single());},[db]);const action=useAction();const [theme,setThemeState]=useState(()=>{try{return localStorage.getItem('wellvie.theme')==='dusk'?'dusk':'light';}catch{return 'light';}});const setTheme=(value:string)=>{setThemeState(value);try{localStorage.setItem('wellvie.theme',value);}catch{}};useEffect(()=>{document.documentElement.dataset.theme=theme;},[theme]);const [online,setOnline]=useState(navigator.onLine);useEffect(()=>{const update=()=>setOnline(navigator.onLine);window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[]);
const [completedPracticeID,setCompletedPracticeID]=useState<number|null>(null);const [unread,setUnread]=useState(0);const [playing,setPlaying]=useState<Practice|null>(null);const [paused,setPaused]=useState(true);const [position,setPosition]=useState(0);const [duration,setDuration]=useState(0);const [audioError,setAudioError]=useState('');const audio=useRef<HTMLAudioElement|null>(null);const playback=useRef(0);const completion=useRef(crypto.randomUUID());const clearAudioSession=useRef<(()=>void)|null>(null);const stop=()=>{playback.current++;clearAudioSession.current?.();clearAudioSession.current=null;audio.current?.pause();if(audio.current){audio.current.removeAttribute('src');audio.current.load();}setPlaying(null);setPosition(0);setDuration(0);};
useEffect(()=>()=>{clearAudioSession.current?.();audio.current?.pause();void db.removeAllChannels();},[db]);
useEffect(()=>{if(!load.data)return;let alive=true;const check=async()=>{try{const member=await rpc<{id:string}|null>(db,'current_member_context');if(!alive)return;if(!member){stop();await signOut();return;}const circles=await rpc<Circle[]>(db,'list_my_circles');if(alive)setUnread(circles.reduce((sum,c)=>sum+c.unread_count,0));}catch{/* Existing content stays in memory during a temporary connection loss. */}};void check();const interval=setInterval(()=>{if(!document.hidden)void check();},15000);window.addEventListener('focus',check);return()=>{alive=false;clearInterval(interval);window.removeEventListener('focus',check);};},[db,load.data?.id]);
const play=async(practice:Practice)=>{
  if(!practice.audio_path)throw new Error('This audio is unavailable.');
  setCompletedPracticeID(null);const element=audio.current!;
  if(playing?.id===practice.id&&element.src){if(element.ended){completion.current=crypto.randomUUID();element.currentTime=0;}await element.play();return;}
  const epoch=++playback.current;
  element.pause();setAudioError('');
  const url=await signedURL(db,'practice-audio',practice.audio_path,7200);
  if(epoch!==playback.current)return;
  clearAudioSession.current?.();
  completion.current=crypto.randomUUID();setPlaying(practice);setPosition(0);setDuration(practice.duration_sec||0);
  element.src=url;element.load();
  clearAudioSession.current=connectAudioSession(element,practice.title,stop,()=>setAudioError('Tap play to continue your practice.'));
  try{await element.play();}catch{setPaused(true);}
};
const complete=async()=>{setCompletedPracticeID(playing?.id??null);if(playing)try{await rpc(db,'record_practice_completion',{p_event_id:completion.current,p_practice_id:playing.id});}catch{setAudioError('Your listening finished, but the completion could not be saved.');}};
const clock=(value:number)=>Math.floor(value/60)+':'+String(Math.floor(value%60)).padStart(2,'0');
if(load.loading&&!load.data)return <Loading/>;if(load.error||!load.data)return <Page title="Your Well-Vie account"><ErrorBox error={load.error||'Your invitation is being prepared. Please try again shortly, or contact Well-Vie.'} retry={load.reload}/><div className="actions"><a className="outline" href="mailto:mckenzie@well-vie.com">Contact Well-Vie</a><button className="outline" onClick={()=>void signOut()}>Sign out</button></div></Page>;
const profile=load.data;const [path,query='']=route.split('?');const active=path.startsWith('/practice')?'/toolkit':path.startsWith('/write')||path.startsWith('/journal/')||path==='/history'?'/journal':path.startsWith('/circle/')?'/circle':path;
const detailTitle=path.startsWith('/practice/')?'Practice':path==='/write'?'New journal entry':path.startsWith('/journal/')?'Journal':({'/intention':'Set intention','/history':'Looking back','/profile':'Your studio','/intake':'Your intake','/guide':'Member guide','/blocked':'Blocked members','/directory':'The circle'} as Record<string,string>)[path];const isDetail=detailTitle!==undefined||path==='/reset';const detailBack=()=>go(path==='/intention'?(['/journal','/history'].includes(new URLSearchParams(query).get('return')||'')?new URLSearchParams(query).get('return')!:'/check-in'):path==='/write'?(new URLSearchParams(query).get('return')||'/journal'):path.startsWith('/practice/')?'/toolkit':path.startsWith('/journal/')||path==='/history'?'/journal':path==='/directory'?'/circle':['/intake','/guide','/blocked'].includes(path)?'/profile':'/check-in');
let content=path==='/check-in'?<CheckIn/>:path==='/toolkit'?<Toolkit/>:path.startsWith('/practice/')?<PracticeView key={path} id={Number(path.split('/')[2])} initiallyComplete={query==='finished'}/>:path==='/journal'?<Journal/>:path==='/write'?<WriteJournal key={route} query={query}/>:path.startsWith('/journal/')?<JournalEntry key={path} id={Number(path.split('/')[2])}/>:path==='/intention'?<IntentionEditor key={route} query={query}/>:path==='/history'?<ReflectionHistory/>:path==='/gatherings'?<Gatherings/>:path==='/reset'?<Reset/>:path==='/circle'?<Circles/>:path.startsWith('/circle/')?<Chat key={path} id={path.split('/')[2]}/>:path==='/directory'?<Directory/>:path==='/profile'?<ProfileView theme={theme} setTheme={setTheme}/>:path==='/intake'?<Intake/>:path==='/blocked'?<Blocked/>:path==='/guide'?<Guide/>:path==='/moderation'?<Moderation/>:<Page eyebrow="More" title="The rest of your space"><div className="stack"><LinkCard title="The Reset" detail="Three weeks, walked together." icon={<Leaf/>} onClick={()=>go('/reset')}/><LinkCard title="Circle" detail="The women beside you." icon={<CircleIcon size={30}/>} onClick={()=>go('/circle')}/><LinkCard title="My profile" detail="Your place in the circle." icon={<UserRound/>} onClick={()=>go('/profile')}/></div></Page>;
if(!profile.welcomed_at)content=<section className="welcome page center"><div className="welcome-mark"><Leaf size={58}/></div><div className="eyebrow">Welcome to Well-Vie</div><h1>We’re so glad you’re here.</h1><p>This is a quiet place. No feeds, no counters, nothing to keep up with.</p><p>A check-in for however you’re arriving.</p><p>A toolkit for when you know what you need, and for when you don’t. We’ll help you find it.</p><p>And a private journal visible only to you. For your eyes only, always.</p><p>Come as you are, as often or as rarely as you need. It’s an honor to walk beside you.</p><h2>with love, the Well-Vie team</h2><button className="primary" disabled={action.busy} onClick={()=>action.run(async()=>{await result(db.from('profiles').update({welcomed_at:new Date().toISOString()}).eq('id',profile.id).select('id').single());await load.reload();})}>Welcome in</button>{action.error&&<ErrorBox error={action.error}/>}</section>;
return <MemberProvider value={{db,profile,refreshProfile:load.reload,go,route,signOut:async()=>{stop();await signOut();},play,playing,paused,pause:()=>audio.current?.pause(),stop,playbackEventID:completion.current,completedPracticeID}}><div className={'app-shell '+(playing?'has-player':'')}><a className="skip-link" href="#main-content">Skip to content</a><header className={'app-header '+(isDetail?'detail-header':'')}>{isDetail?<><button className="detail-back" aria-label="Back" onClick={detailBack}><ChevronLeft size={26}/></button><span>{detailTitle||''}</span></>:<>{profile.welcomed_at&&<NavigationDrawer active={active} unread={unread} go={go} theme={theme} setTheme={setTheme}/>}<button className="brand-button" aria-label="Well-Vie home" onClick={()=>go('/check-in')}><Brand/></button><button className="icon-button inbox" aria-label={'Circle'+(unread?', '+unread+' unread messages':'')} onClick={()=>go('/circle')}><CircleIcon count={unread}/></button></>}</header>{!online&&<div className="offline" role="status"><WifiOff size={16}/>You’re offline. Reconnect to load or save your content.</div>}<main id="main-content">{content}</main><audio ref={audio} preload="metadata" onPlay={()=>setPaused(false)} onPause={()=>setPaused(true)} onTimeUpdate={e=>setPosition(e.currentTarget.currentTime)} onLoadedMetadata={e=>setDuration(Number.isFinite(e.currentTarget.duration)?e.currentTarget.duration:0)} onEnded={()=>void complete()} onError={()=>setAudioError('We couldn’t load this audio. Open the practice and try again.')}/>{playing&&<aside className="mini-player" aria-label="Practice audio player"><div className="row"><Leaf className="player-leaf" size={26}/><div className="grow"><strong>{cleanCopy(playing.title)}</strong><small>{clock(position)} / {clock(duration)}</small></div><button className="icon-button" aria-label="Back 15 seconds" onClick={()=>{if(audio.current)audio.current.currentTime=Math.max(0,position-15);}}><SkipBack size={18}/></button><button className="icon-button player-toggle" aria-label={paused?'Play':'Pause'} onClick={()=>{if(paused)void audio.current?.play().catch(()=>setAudioError('Tap the practice to reload the audio.'));else audio.current?.pause();}}>{paused?<Play size={20}/>:<Pause size={20}/>}</button><button className="icon-button" aria-label="Close audio player" onClick={stop}><X size={19}/></button></div><input type="range" aria-label="Audio position" min={0} max={duration||1} value={Math.min(position,duration||1)} step={1} onChange={e=>{if(audio.current)audio.current.currentTime=Number(e.target.value);}}/>{audioError&&<p className="small" role="alert">{audioError}</p>}</aside>}</div></MemberProvider>;
}
createRoot(document.getElementById('root')!).render(<StrictMode><ClerkProvider publishableKey={config.clerkKey} telemetry={{disabled:true}} appearance={{variables:{colorPrimary:'#3e4e35',colorForeground:'#3e4e35',colorBackground:'#ffffff',fontFamily:'Poppins, sans-serif',borderRadius:'16px'},elements:{rootBox:{width:'100%'},cardBox:{width:'100%',boxShadow:'none',border:'none'},card:{boxShadow:'none',padding:'16px 0'},headerTitle:{display:'none'},headerSubtitle:{display:'none'},footerAction__signIn:{display:'none'},footerAction__signUp:{display:'none'},logoBox:{display:'none'}}}}><Connected/></ClerkProvider></StrictMode>);
if(import.meta.env.PROD&&'serviceWorker'in navigator)window.addEventListener('load',()=>{void navigator.serviceWorker.register('/app/sw.js',{scope:'/app/'}).catch(()=>{});});
