import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowLeft,ChevronRight,LoaderCircle} from 'lucide-react';
import {safeError,cleanCopy} from './data';
// SwiftUI avoids an isolated final word. Apply that narrowly instead of
// text-wrap:pretty, whose paragraph balancing differs between Safari and Chrome.
export const nativeWrap=(text:string)=>text.trim().split(/\s+/).length>2?text.replace(/(\S+)\s+(\S+)$/,(_,a:string,b:string)=>a.length+b.length<28?a+'\u00a0'+b:a+' '+b):text;
export function Page({eyebrow,title,intro,children,back,action,eyebrowAction,topContent,className=''}: {eyebrow?:string;title:string;intro?:string;children?:ReactNode;back?:()=>void;action?:ReactNode;eyebrowAction?:ReactNode;topContent?:ReactNode;className?:string}){return <section className={'page '+className}>{back&&<button className="back" onClick={back}><ArrowLeft size={18}/>Back</button>}{topContent}<header className="page-heading"><div className="page-eyebrow-row">{eyebrow&&<div className="eyebrow">{cleanCopy(eyebrow)}</div>}{eyebrowAction}</div><div className="page-title-row"><h1>{nativeWrap(cleanCopy(title))}</h1>{action}</div>{intro&&<p>{nativeWrap(cleanCopy(intro))}</p>}</header><div className="page-content">{children}</div></section>;}
export function Loading(){return <div className="loading" role="status"><LoaderCircle className="spin" size={26}/><span>Gathering your space…</span></div>;}
export function ErrorBox({error,retry}:{error:unknown;retry?:()=>void}){return <div className="error" role="alert"><p>{typeof error==='string'?error:safeError(error)}</p>{retry&&<button className="outline" onClick={retry}>Try again</button>}</div>;}
export function Empty({title,children,icon}:{title:string;children?:ReactNode;icon?:ReactNode}){return <div className="card empty">{icon}<h2>{title}</h2>{children}</div>;}
export function LinkCard({title,detail,icon,onClick}:{title:string;detail?:string;icon?:ReactNode;onClick:()=>void}){return <button className="card link-card" onClick={onClick}>{icon&&<span className="tile-icon">{icon}</span>}<span className="grow"><strong>{cleanCopy(title)}</strong>{detail&&<span className="muted">{cleanCopy(detail)}</span>}</span><ChevronRight size={20}/></button>;}
export function useLoad<T>(load:()=>Promise<T>,keys:unknown[]=[]){const [data,setData]=useState<T>();const [error,setStoredError]=useState<string>();const setError=(e:unknown)=>setStoredError(e===undefined?undefined:typeof e==='string'?e:safeError(e));const [loading,setLoading]=useState(true);const ref=useRef(load);ref.current=load;const generation=useRef(0);const reload=useCallback(async()=>{const id=++generation.current;setError(undefined);setLoading(true);try{const next=await ref.current();if(id===generation.current)setData(next);}catch(e){if(id===generation.current)setError(e);}finally{if(id===generation.current)setLoading(false);}},keys);useEffect(()=>{setData(undefined);void reload();return()=>{generation.current++;};},[reload]);return {data,setData,error,loading,reload};}
export function useAction(){const [busy,setBusy]=useState(false);const [error,setStoredError]=useState<string>();const setError=(e:unknown)=>setStoredError(e===undefined?undefined:typeof e==='string'?e:safeError(e));const lock=useRef(false);const run=async(fn:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError(undefined);try{await fn();}catch(e){setError(e);}finally{lock.current=false;setBusy(false);}};return {busy,error,setError,run};}
export function useRoute(){const read=()=>{try{return decodeURI(location.hash.slice(1)||'/check-in');}catch{return '/check-in';}};const [route,setRoute]=useState(read);const current=useRef(route);current.current=route;useEffect(()=>{const update=()=>{const next=read();if(next===current.current)return;if(!window.dispatchEvent(new Event('wellvie-before-navigate',{cancelable:true}))){history.replaceState(null,'','#'+current.current);return;}current.current=next;setRoute(next);window.scrollTo(0,0);};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);const go=(path:string)=>{location.hash=path;};return {route,go};}
export const dateLabel=(date:string)=>new Date(date).toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'});
export const timeLabel=(date:string)=>new Date(date).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'});
