import {useMemo,useRef,useState} from 'react';
import {ArrowDown,ArrowUp,Plus,HardDrive} from 'lucide-react';
import {ContentEditor,newDraft} from './editor';
import {Alert,Paged,SearchField,date,matches,message} from './shared';
import type {AdminRepository,AudioInventory,Draft,EditableTable,Snapshot} from './types';
const labels={practices:'practice',feelings:'feeling',program_weeks:'Reset week',events:'gathering'};
export function Content({table,data,repository,refresh,go}:{table:EditableTable;data:Snapshot;repository:AdminRepository;refresh:()=>void;go:(path:string)=>void}){
  const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[draft,setDraft]=useState<Draft>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false);
  const source=table==='practices'?data.practices:table==='feelings'?data.feelings:table==='events'?data.gatherings:data.weeks;
  const rows=useMemo(()=>source.filter(r=>matches(query,'label'in r?r.label:r.title,'description'in r?r.description:'' )&&(filter==='all'||'active'in r&&r.active===(filter==='active'))),[source,query,filter]);
  const reorder=async(index:number,delta:number)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');const ids=data.feelings.map(f=>f.id);[ids[index],ids[index+delta]]=[ids[index+delta],ids[index]];try{await repository.reorderFeelings(ids);refresh();}catch(e){setError(message(e));}finally{lock.current=false;setBusy(false);}};
  return <><div className="studio-toolbar"><button className="primary" disabled={busy||table==='practices'&&!data.needs.length} onClick={()=>setDraft(newDraft(table,data))}><Plus size={18}/>New {labels[table]}</button>{table==='practices'&&<button className="outline" onClick={()=>go('/studio/recordings')}><HardDrive size={18}/>Recording storage check</button>}</div><SearchField value={query} onChange={setQuery} label={'Search '+(table==='program_weeks'?'Reset weeks':table==='events'?'gatherings':table)}/>{table!=='program_weeks'&&<div className="studio-tabs" role="group" aria-label="Availability filter">{[['all','All'],['active',table==='feelings'?'Available':'Published'],['retired',table==='feelings'?'Hidden':'Draft / retired']].map(([key,label])=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</div>}<Alert error={error}/>
    <Paged items={rows} render={r=><article className="card studio-record" key={r.id}><button className="studio-record-button" disabled={busy} onClick={()=>setDraft({...r})}><h2>{'label'in r?r.label:r.title}</h2>{'week_number'in r&&<p className="small">Week {r.week_number}</p>}{'starts_at'in r&&<p className="small">{new Date(r.starts_at).toLocaleString()} · {r.kind}</p>}{'need_slug'in r&&<p className="small">{data.needs.find(n=>n.slug===r.need_slug)?.label??r.need_slug} · {r.kind==='audio'?'Audio':'Written'}</p>}{'description'in r&&<p>{r.description}</p>}{'active'in r&&<span className="studio-status">{r.active?(table==='feelings'?'Available':'Published'):(table==='feelings'?'Hidden':'Draft / retired')}</span>}<span className="small">Edit {labels[table]}</span></button>{table==='feelings'&&<div className="actions"><button className="icon-button" disabled={busy||data.feelings[0]?.id===r.id} aria-label={'Move '+('label'in r?r.label:'feeling')+' up'} onClick={()=>void reorder(data.feelings.findIndex(f=>f.id===r.id),-1)}><ArrowUp size={18}/></button><button className="icon-button" disabled={busy||data.feelings.at(-1)?.id===r.id} aria-label={'Move '+('label'in r?r.label:'feeling')+' down'} onClick={()=>void reorder(data.feelings.findIndex(f=>f.id===r.id),1)}><ArrowDown size={18}/></button></div>}</article>}/>
    {table==='feelings'&&<section className="card studio-section"><h2>In members’ own words</h2><p className="small">Only the phrase and its usage count are shown.</p><Paged items={data.customFeelings} empty="No custom feelings yet." render={f=><p key={f.word}>{f.word} <span className="muted">· {f.uses}</span></p>}/></section>}
    {draft&&<ContentEditor table={table} initial={draft} data={data} repository={repository} onClose={()=>setDraft(undefined)} onSaved={()=>{setDraft(undefined);refresh();}}/>}
  </>;
}
export function Intake({data}:{data:Snapshot}){
  const [query,setQuery]=useState('');const rows=useMemo(()=>data.intake.filter(r=>matches(query,data.members.find(m=>m.id===r.user_id)?.name,data.invites.find(i=>i.accepted_by===r.user_id)?.email)),[data,query]);
  return <><SearchField label="Search intake by member" value={query} onChange={setQuery}/><Paged items={rows} empty="No intake responses yet." render={r=><article className="card studio-record" key={r.id}><h2>{data.members.find(m=>m.id===r.user_id)?.name??'Former member'}</h2><p className="small">{data.invites.find(i=>i.accepted_by===r.user_id)?.email} · {date(r.created_at)}</p>{[['What are you looking for?',r.looking_for],['Why now?',r.why],['How do you hope to be supported?',r.how]].map(([title,answer])=><section key={title}><h3>{title}</h3><p className="pre-wrap">{answer||'Not provided'}</p></section>)}</article>}/></>;
}
export function Recordings({repository}:{repository:AdminRepository}){
  const [data,setData]=useState<AudioInventory>(),[busy,setBusy]=useState(false),[error,setError]=useState('');
  return <><p>This is a read-only storage inventory. Referenced recordings and uploads from the last seven days are kept separate. No files are deleted.</p><button className="outline" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{setData(await repository.inventory());}catch(e){setError(message(e));}finally{setBusy(false);}}}>{busy?'Checking recordings…':data?'Refresh inventory':'Check recordings'}</button><Alert error={error}/>{data&&<><p className="small">{data.scanned} files checked · {data.referenced} referenced by practices · {new Date(data.scannedAt).toLocaleString()}</p>{[['Unreferenced recordings older than seven days',data.candidates],['Inside the seven-day grace period',data.recent],['Unknown age',data.unknown]].map(([title,items])=><section className="card studio-section" key={String(title)}><h2>{String(title)}</h2><Paged items={items as AudioInventory['candidates']} render={file=><div key={file.path}><p className="studio-file-path">{file.path}</p><p className="small">{file.createdAt?date(file.createdAt):'Creation date unavailable'}</p></div>}/></section>)}</>}</>;
}
