import {confirmAction} from '../confirm-dialog';
import {useMemo,useRef,useState} from 'react';
import {ArrowDown,ArrowUp,X} from 'lucide-react';
import {Alert,Field,SearchField,Toggle,matches,message,useEditorGuard} from './shared';
import type {AdminRepository,Snapshot} from './types';
export function Curation({data,repository,refresh}:{data:Snapshot;repository:AdminRepository;refresh:()=>void}){
  const feelings=data.feelings.filter(f=>f.active),needs=data.needs.filter(n=>n.active);
  const [feeling,setFeeling]=useState(feelings[0]?.id??0),[need,setNeed]=useState(needs[0]?.id??0),[selection,setSelection]=useState<number[]|null>(null),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false);
  const initial=useMemo(()=>data.curation.filter(c=>c.feeling_id===feeling&&c.need_id===need).sort((a,b)=>a.sort_order-b.sort_order).map(c=>c.practice_id),[data,feeling,need]);
  const ids=selection??initial,dirty=selection!==null&&JSON.stringify(selection)!==JSON.stringify(initial);useEditorGuard(dirty,busy);
  const choosePair=async(nextFeeling:number,nextNeed:number)=>{if(busy)return;if(dirty&&!await confirmAction({title:'Discard curation changes?',message:'The order you chose has not been saved.',confirmLabel:'Discard changes',cancelLabel:'Keep editing',danger:true}))return;setFeeling(nextFeeling);setNeed(nextNeed);setSelection(null);setError('');};
  const move=(index:number,delta:number)=>{const next=[...ids];[next[index],next[index+delta]]=[next[index+delta],next[index]];setSelection(next);};
  const eligible=data.practices.filter(p=>p.active&&matches(query,p.title,p.description));
  const matching=eligible.filter(p=>p.need_slug===needs.find(n=>n.id===need)?.slug),other=eligible.filter(p=>!matching.includes(p));
  if(!feelings.length||!needs.length)return <p>At least one active feeling and need is required to curate an offering.</p>;
  return <><details className="card studio-coverage"><summary>Curation coverage</summary><div className="studio-coverage-scroll"><table><caption>Practices offered for each feeling and need</caption><thead><tr><th>Feeling</th>{needs.map(n=><th key={n.id}>{n.label}</th>)}</tr></thead><tbody>{feelings.map(f=><tr key={f.id}><th>{f.label}</th>{needs.map(n=>{const count=data.curation.filter(c=>c.feeling_id===f.id&&c.need_id===n.id).length;return <td key={n.id}><button disabled={busy} onClick={()=>choosePair(f.id,n.id)} aria-label={`${f.label}, ${n.label}: ${count?count+' practices':'fallback'}`}>{count||'Fallback'}</button></td>;})}</tr>)}</tbody></table></div></details><fieldset disabled={busy} className="studio-fields card"><Field label="Feeling"><select value={feeling} onChange={e=>choosePair(Number(e.target.value),need)}>{feelings.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></Field><Field label="What she asks for"><select value={need} onChange={e=>choosePair(feeling,Number(e.target.value))}>{needs.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></Field></fieldset>
    <section className="studio-section card"><h2>Offered in this order · {ids.length}</h2>{!ids.length&&<p>Members receive the same-need fallback when no practices are selected.</p>}{ids.map((id,index)=><div className="studio-curated-row" key={id}><span>{index+1}. {data.practices.find(p=>p.id===id)?.title??'Unavailable practice'}{!data.practices.find(p=>p.id===id)?.active?' · retired':''}</span><div><button className="icon-button" disabled={busy||!index} aria-label={'Move practice '+(index+1)+' earlier'} onClick={()=>move(index,-1)}><ArrowUp size={18}/></button><button className="icon-button" disabled={busy||index===ids.length-1} aria-label={'Move practice '+(index+1)+' later'} onClick={()=>move(index,1)}><ArrowDown size={18}/></button><button className="icon-button" disabled={busy} aria-label={'Remove practice '+(index+1)} onClick={()=>setSelection(ids.filter(i=>i!==id))}><X size={18}/></button></div></div>)}</section>
    <SearchField value={query} onChange={setQuery} label="Search practices"/>{[['Matching the requested support',matching],['Other practice types',other]].map(([title,practices])=><section className="card studio-section" key={String(title)}><h2>{String(title)}</h2>{(practices as typeof eligible).map(p=><Toggle key={p.id} label={p.title} checked={ids.includes(p.id)} disabled={busy||ids.length>=3&&!ids.includes(p.id)} onChange={checked=>setSelection(checked?[...ids,p.id]:ids.filter(id=>id!==p.id))}/>)}</section>)}<Alert error={error}/><button className="primary" disabled={busy||!dirty} onClick={async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await repository.curate(feeling,need,ids);setSelection(null);refresh();}catch(e){setError(message(e));}finally{lock.current=false;setBusy(false);}}}>{busy?'Saving…':'Save curation'}</button>
  </>;
}
