import {confirmAction} from '../confirm-dialog';
import {useMemo,useRef,useState} from 'react';
import {Plus,Shield,UserRound} from 'lucide-react';
import {Alert,Confirm,EditorShell,Field,Paged,SearchField,Toggle,date,matches,message,type Decision} from './shared';
import type {AdminRepository,Snapshot,ProgrammeAccess} from './types';
export function Members({data,repository,memberID,refresh}:{data:Snapshot;repository:AdminRepository;memberID:string;refresh:()=>void}){
  const [query,setQuery]=useState(''),[tab,setTab]=useState('joined'),[invite,setInvite]=useState(false),[decision,setDecision]=useState<Decision>(),[access,setAccess]=useState<{name:string;id:string|null;email:string|null;current:ProgrammeAccess}>();
  const members=useMemo(()=>data.members.filter(m=>matches(query,m.name,data.invites.find(i=>i.accepted_by===m.id)?.email)),[data,query]);
  const invites=useMemo(()=>data.invites.filter(i=>!i.accepted_by&&matches(query,i.name,i.email)),[data,query]);
  return <><div className="studio-toolbar"><button className="primary" onClick={()=>setInvite(true)}><Plus size={18}/>Invite member</button><div className="studio-tabs" role="group" aria-label="Member lists"><button aria-pressed={tab==='joined'} onClick={()=>setTab('joined')}>Joined ({data.members.length})</button><button aria-pressed={tab==='waiting'} onClick={()=>setTab('waiting')}>Waiting to join ({data.invites.filter(i=>!i.accepted_by).length})</button></div></div><SearchField value={query} onChange={setQuery} label="Search members or emails"/>
    {tab==='joined'?<Paged items={members} render={m=><article className="card studio-record" key={m.id}><div className="row"><UserRound size={24}/><div className="grow"><h2>{m.name}{m.id===memberID?' (you)':''}</h2><p className="small">{data.invites.find(i=>i.accepted_by===m.id)?.email}</p></div>{m.is_admin&&<Shield aria-label="Founder" size={20}/>}</div><p className="small">{m.is_admin?'Founder':m.programme_access==='app_only'?'App only':'App + programme'} · Joined {date(m.created_at)}</p><div className="actions">{!m.is_admin&&<button className="outline" onClick={()=>setAccess({name:m.name,id:m.id,email:null,current:m.programme_access??'programme'})}>Change access</button>}<button className="outline" disabled={m.id===memberID} onClick={()=>setDecision({title:m.is_admin?'Remove founder access?':'Grant founder access?',description:m.is_admin?`${m.name} will keep member access but can no longer manage Studio.`:`${m.name} will be able to manage invitations, members, private intake, content and moderation.`,label:m.is_admin?'Make member':'Grant founder access',run:()=>repository.memberAction('role',m.id,m.is_admin?'member':'admin')})}>{m.is_admin?'Make member':'Grant founder access'}</button><button className="outline danger" disabled={m.id===memberID} onClick={()=>setDecision({title:'Remove '+m.name+'?',description:'This permanently removes their sign-in, profile, private journal, check-ins, intentions and intake. This cannot be undone.',label:'Permanently remove member',typeToConfirm:'REMOVE',danger:true,run:()=>repository.memberAction('remove',m.id)})}>Remove member</button></div></article>}/>:<Paged items={invites} empty="No invitations are waiting." render={i=><article className="card studio-record" key={i.email}><h2>{i.name}</h2><p>{i.email}</p><p className="small">{i.is_admin?'Founder':i.programme_access==='app_only'?'App only':'App + programme'} · Invited {date(i.created_at)}</p><div className="actions">{!i.is_admin&&<button className="outline" onClick={()=>setAccess({name:i.name,id:null,email:i.email,current:i.programme_access??'programme'})}>Change access</button>}<button className="outline" onClick={()=>setDecision({title:'Resend invitation?',description:'An invitation email will be sent to '+i.email+'.',label:'Send invitation',run:()=>repository.invite(i.name,i.email,i.is_admin,i.programme_access??'programme')})}>Resend invitation</button><button className="outline danger" onClick={()=>setDecision({title:'Revoke invitation?',description:i.email+' will no longer be able to join using this invitation.',label:'Revoke invitation',danger:true,run:()=>repository.memberAction('revoke',i.email)})}>Revoke</button></div></article>}/>}
    {access&&<AccessEditor target={access} repository={repository} onClose={()=>setAccess(undefined)} onSaved={()=>{setAccess(undefined);refresh();}}/>}{invite&&<Invite repository={repository} onClose={()=>setInvite(false)} onSaved={()=>{setInvite(false);refresh();}}/>}{decision&&<Confirm decision={decision} onClose={()=>setDecision(undefined)} onDone={()=>{setDecision(undefined);refresh();}}/>}
  </>;
}
function Invite({repository,onClose,onSaved}:{repository:AdminRepository;onClose:()=>void;onSaved:()=>void}){
  const [name,setName]=useState(''),[email,setEmail]=useState(''),[admin,setAdmin]=useState(false),[programme,setProgramme]=useState<ProgrammeAccess>('programme'),[busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false),id=useRef('studio-invite-'+crypto.randomUUID());
  return <EditorShell title="Invite member" busy={busy} dirty={!!name||!!email||admin} onClose={onClose} action={<button type="submit" form={id.current} disabled={busy}>{busy?'Sending…':'Send'}</button>}><p>An invitation email will be sent to this address. Members can then sign in using their email code.</p><form id={id.current} onSubmit={async e=>{e.preventDefault();if(lock.current)return;if(admin&&!await confirmAction({title:'Give founder access?',message:'This member can manage content, invitations, other members and private intake.',confirmLabel:'Give founder access'}))return;lock.current=true;setBusy(true);setError('');try{await repository.invite(name,email,admin,programme);onSaved();}catch(e){setError(message(e)+' If delivery failed, refresh Members to check the saved invitation before sending again.');}finally{lock.current=false;setBusy(false);}}}><fieldset disabled={busy} className="studio-fields"><Field label="Name"><input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Email"><input type="email" required autoCapitalize="none" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Member access"><select value={programme} disabled={admin} onChange={e=>setProgramme(e.target.value as ProgrammeAccess)}><option value="programme">App + programme</option><option value="app_only">App only</option></select><p className="small">{admin?'Founders can access all programme content.':programme==='app_only'?'Everyday tools, without The Reset, calls or replays.':'Includes The Reset, gatherings and replays.'}</p></Field><Toggle label="Give founder access" checked={admin} onChange={setAdmin}/></fieldset><Alert error={error}/></form></EditorShell>;
}

function AccessEditor({target,repository,onClose,onSaved}:{target:{name:string;id:string|null;email:string|null;current:ProgrammeAccess};repository:AdminRepository;onClose:()=>void;onSaved:()=>void}) {
  const [access,setAccess]=useState(target.current),[busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false);
  const save=async()=>{if(lock.current||access===target.current)return;lock.current=true;setBusy(true);setError('');try{await repository.programmeAccess(target.id,target.email,access,target.current);onSaved();}catch(e){setError(message(e));}finally{lock.current=false;setBusy(false);}};
  return <EditorShell title="Member access" busy={busy} dirty={access!==target.current} onClose={onClose} action={<button disabled={busy||access===target.current} onClick={()=>void save()}>{busy?'Saving…':'Save'}</button>}><h3>{target.name}</h3><Field label="Member access"><select disabled={busy} value={access} onChange={e=>setAccess(e.target.value as ProgrammeAccess)}><option value="programme">App + programme</option><option value="app_only">App only</option></select></Field><p>{access==='app_only'?'Everyday tools, without The Reset, calls or replays.':'Includes The Reset, gatherings and replays.'}</p><Alert error={error}/></EditorShell>;
}
