import {confirmAction} from '../confirm-dialog';
import {useEffect,useRef,useState} from 'react';
import {Shield} from 'lucide-react';
import {Alert,EditorShell,Field,Paged,Toggle,date,message} from './shared';
import type {AdminRepository,Member,Report,Snapshot} from './types';
import {prompts} from '../profile';
export function Safety({data,repository,refresh,go}:{data:Snapshot;repository:AdminRepository;refresh:()=>void;go:(path:string)=>void}){
  const [review,setReview]=useState<Member|Report>(),[summary,setSummary]=useState<Awaited<ReturnType<AdminRepository['safetySummary']>>>();
  useEffect(()=>{let active=true;void repository.safetySummary().then(value=>{if(active)setSummary(value);}).catch(()=>{});return()=>{active=false;};},[repository,data]);
  const sections=[['Profile approvals',data.members.filter(m=>m.circle_moderation_status==='pending'&&m.profile_visible)],['Hidden profiles',data.members.filter(m=>m.circle_moderation_status==='hidden')]] as const;
  return <><button className="outline" onClick={()=>go('/studio/chat-review')}><Shield size={20}/>{summary?`Chat: ${summary.chat_reports} reports · ${summary.chat_approvals} awaiting review`:'Chat review & reports'}</button><p className="small">Profile approvals are routine checks of shared profiles, not complaints. Enable notifications in Circle safety on your iPhone for report alerts and grouped approval reminders.</p>{sections.map(([title,members])=><section key={title} className="studio-section"><h2>{title} · {members.length}</h2><Paged items={members} empty="No profiles here." render={m=><button key={m.id} className="card studio-record studio-record-button" onClick={()=>setReview(m)}><strong>{m.name||'Member'}</strong><span className="small">{m.profile_visible?'Shared profile':'Member chose private'} · Revision {m.circle_content_revision}</span><span>Review profile</span></button>}/></section>)}<section className="studio-section"><h2>Profile reports</h2><Paged items={data.reports.filter(r=>['open','reviewing'].includes(r.status))} empty="No open reports." render={r=><button key={r.id} className="card studio-record studio-record-button" onClick={()=>setReview(r)}><strong>{r.reason.replaceAll('_',' ')}</strong><span>{r.profile_snapshot.name||'Member'} · {date(r.created_at)}</span><span className="small">Reported by {data.members.find(m=>m.id===r.reporter_id)?.name||'Former member'}</span></button>}/></section>{review&&<Review key={'profile_snapshot'in review?'report-'+review.id:'profile-'+review.id} record={review} repository={repository} onClose={()=>setReview(undefined)} onSaved={()=>{setReview(undefined);refresh();}}/>}</>;
}
function Review({record,repository,onClose,onSaved}:{record:Member|Report;repository:AdminRepository;onClose:()=>void;onSaved:()=>void}){
  const isReport='profile_snapshot'in record,profile=isReport?record.profile_snapshot:record;
  const [note,setNote]=useState(''),[hide,setHide]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[photo,setPhoto]=useState(''),[photoReady,setPhotoReady]=useState(!profile.photo_path),[attempt,setAttempt]=useState(0);const lock=useRef(false);
  useEffect(()=>{let alive=true;if(!profile.photo_path)return;setPhotoReady(false);void repository.signedUrl('profile-photos',profile.photo_path).then(url=>{if(alive)setPhoto(url);}).catch(e=>{if(alive)setError(message(e));});return()=>{alive=false;};},[profile.photo_path,repository,attempt]);
  const act=async(status:'approved'|'hidden'|'resolved'|'dismissed')=>{
    if(lock.current)return;
    if(status==='hidden'||isReport){const detail=status==='hidden'?'Hide this profile from Circle?':status==='dismissed'?'Dismiss this report without changing the profile?':hide?'Resolve this report and hide the profile?':'Resolve this report without hiding the profile?';if(!await confirmAction({title:detail,confirmLabel:status==='hidden'?'Hide profile':status==='dismissed'?'Dismiss report':'Resolve report',danger:status==='hidden'||status==='resolved'&&hide}))return;}
    lock.current=true;setBusy(true);setError('');try{if(isReport)await repository.resolve(record,status as 'resolved'|'dismissed',note,status==='resolved'&&hide);else await repository.moderate(record,status as 'approved'|'hidden',note);onSaved();}catch(e){setError(message(e)+' Close and refresh before reviewing the latest version again.');}finally{lock.current=false;setBusy(false);}
  };
  return <EditorShell title={isReport?'Review report':'Review profile'} busy={busy} dirty={!!note} onClose={onClose}><h3>{profile.name||'Member'}</h3>{isReport&&<><p>{record.reason.replaceAll('_',' ')}</p><p className="pre-wrap">{record.details}</p></>}{[...(['intention','about','hoping'] as const).map(key=>[key,profile[key]]),...prompts.map(([key,label])=>[label,profile.profile_prompts?.[key]])].filter(([,value])=>value).map(([label,value])=><section key={label}><h4>{label}</h4><p className="pre-wrap">{value}</p></section>)}{profile.photo_path&&<section>{photo&&<img className="studio-review-photo" src={photo} alt={'Submitted profile photo for '+profile.name} onLoad={()=>setPhotoReady(true)} onError={()=>{setPhotoReady(false);setError('The photo could not load. Review it before approving.');}}/>}{!photoReady&&<button className="outline" disabled={busy} onClick={()=>setAttempt(n=>n+1)}>Retry photo</button>}</section>}<Field label="Review note" hint={isReport?'Internal resolution note.':'This note may be shown to the member.'}><textarea rows={3} maxLength={isReport?1000:500} disabled={busy} value={note} onChange={e=>setNote(e.target.value)}/></Field>{isReport&&<Toggle label="Also hide the reported profile" checked={hide} disabled={busy} onChange={setHide}/>}<Alert error={error}/><div className="actions"><button className="outline" disabled={busy||(isReport&&!photoReady)} onClick={()=>void act(isReport?'dismissed':'hidden')}>{isReport?'Dismiss report':'Hide profile'}</button><button className="primary" disabled={busy||(!isReport&&!photoReady)||isReport&&!hide&&!photoReady} onClick={()=>void act(isReport?'resolved':'approved')}>{isReport?'Resolve report':'Approve profile'}</button></div></EditorShell>;
}
